server:
  port: 7001

spring:
  profiles:
    active: @spring.active@
  datasource:
    url: jdbc:mysql://47.110.64.206/supermarket?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: Mysql@123

#mp配置
mybatis-plus:
  type-aliases-package: com.chenhuan.supermarket.modular



#profile配置